name: macOS workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build app
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: make